### ISSUE TITLE
Help/Error

### ISSUE THREAD

**Issue by therobokedi** [mcbeany-pm-pl/NBTEditor#1]
Me giving error pls help

**Comment by Mcbeany** [comment]
Please describe your problem in more detail, thanks

**Comment by therobokedi** [comment]
Oke one min

**Comment by therobokedi** [comment]
Error: Class "Mcbeany\NBTEditor\libs\dktapps\pmforms\MenuForm" not found
File: plugins/NBTEditor (1).phar/src/menus/ContainerTagMenu
Line: 27
Type: Error
Backtrace:
#0 plugins/NBTEditor (1).phar/src/menus/BaseTagMenu(38): Mcbeany\NBTEditor\menus\ContainerTagMenu->getForm()
#1 plugins/NBTEditor (1).phar/src/NBTEditor(71): Mcbeany\NBTEditor\menus\BaseTagMenu->send()
#2 plugins/NBTEditor (1).phar/src/NBTEditor(55): Mcbeany\NBTEditor\NBTEditor::openEditor(object Mcbeany\NBTEditor\sessions\Session#124433, object pocketmine\nbt\tag\CompoundTag#123027)
#3 pmsrc/src/command/PluginCommand(54): Mcbeany\NBTEditor\NBTEditor->onCommand(object pocketmine\player\Player#110945, object pocketmine\command\PluginCommand#26714, string[4] nbte, array[0])
#4 pmsrc/src/command/SimpleCommandMap(220): pocketmine\command\PluginCommand->execute(object pocketmine\player\Player#110945, string[4] nbte, array[0])
#5 pmsrc/src/Server(1409): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#110945, string[4] nbte)
#6 pmsrc/src/player/Player(1402): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#110945, string[4] nbte)
#7 pmsrc/src/network/mcpe/handler/InGamePacketHandler(754): pocketmine\player\Player->chat(string[5] /nbte)
#8 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(51): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#125668)
#9 pmsrc/src/network/mcpe/NetworkSession(398): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object CLADevs\VanillaX\network\InGamePacketHandlerX#123128)
#10 pmsrc/src/network/mcpe/NetworkSession(361): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#125668, string[26] M./nbte.AI].M:a..'....M...)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[29] ..e..K*Iep.....J|.[...,......)
#12 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[38] ....i.{B.....o..._.W.7Y.....4....-....)
#13 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#32186)
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#16 pmsrc/src/Server(1661): pocketmine\snooze\SleeperHandler->sleepUntil(double 1653733521.9057)
#17 pmsrc/src/Server(1047): pocketmine\Server->tickProcessor()
#18 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#19 pmsrc/src/PocketMine(327): pocketmine\server()
#20 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[18] use function array_values;
[19] use function count;
[20] use function sprintf;
[21] use function strval;
[22] use function ucfirst;
[23] 
[24] class ContainerTagMenu extends BaseTagMenu{
[25] 
[26] 	protected function getForm() : BaseForm{
[27] 		return new MenuForm(
[28] 			NBTEditor::NBTEDITOR,
[29] 			"Select a tag to edit",
[30] 			$this->getElements(),
[31] 			function(Player $player, int $selectedOption) : void{
[32] 				if(!$this->isViewer($player)){
[33] 					return;
[34] 				}
[35] 				$this->onResponse($selectedOption);
[36] 			},
[37] 			function(Player $player) : void{

**Comment by therobokedi** [comment]
please help me i want to use this great plugin

**Comment by therobokedi** [comment]
Pls _helpp**plss**_

**Comment by Mcbeany** [comment]
Fixed

**Comment by therobokedi** [comment]
Ok :)
